import React from 'react';
import { format } from 'date-fns';
import QRCode from 'react-qr-code';

interface EWayBillItem {
  product_name: string;
  hsn_code: string;
  quantity: number;
  unit: string;
  value: number;
}

interface Client {
  name: string;
  email: string;
  gstin: string;
  address: string;
  state: string;
  postal_code: string;
  hide_contact_details?: boolean;
}

interface Profile {
  company_name: string;
  business_address: string;
  gstin: string;
  phone: string;
}

interface DigitalStampProps {
  text?: string;
}

const DigitalStamp: React.FC<DigitalStampProps> = ({ text = "DIGITALLY SIGNED" }) => (
  <div className="relative w-24 h-24 flex items-center justify-center opacity-30 select-none pointer-events-none">
    <div className="absolute w-20 h-20 border-4 border-blue-900 rounded-full flex items-center justify-center -rotate-12">
      <div className="text-[8px] font-black text-blue-900 border-2 border-blue-900 px-1 text-center leading-tight uppercase">
        {text}
      </div>
    </div>
    <div className="absolute w-full h-full border-2 border-dashed border-blue-900/40 rounded-full animate-spin-slow"></div>
  </div>
);

interface EWayBillData {
  document_type: string;
  document_number: string;
  document_date: string;
  transaction_type: string;
  from_address?: string;
  from_gstin?: string;
  to_address?: string;
  to_gstin?: string;
  vehicle_number?: string;
  transport_mode: string;
  distance?: string;
  transporter_name?: string;
  total_value: number;
  eway_bill_no?: string;
  valid_until?: string;
}

interface EWayBillTemplateProps {
  eWayBillData: EWayBillData;
  client: Client;
  items: EWayBillItem[];
  profile: Profile;
}

export const EWayBillTemplate: React.FC<EWayBillTemplateProps> = ({
  eWayBillData,
  client,
  items,
  profile,
}) => {
  return (
    <div className="invoice-template bg-white text-black max-w-4xl mx-auto p-4 border border-black font-sans" style={{ minHeight: '297mm', width: '210mm', fontSize: '11px', lineHeight: '1.4' }}>
      <div className="flex border-b border-black pb-2 mb-4">
        <div className="w-[80%] text-center">
           <h1 className="text-xl font-bold uppercase underline">E-WAY BILL</h1>
           <p className="text-[10px] font-bold mt-1">(Generated through e-Way Bill System as per GST Rules)</p>
           <div className="text-[10px] mt-1 italic opacity-70">Authenticated Digital Copy for Transport Movement</div>
        </div>
        <div className="w-[20%] flex flex-col items-center justify-center p-1 border border-black rounded bg-white">
           {/* Primary E-Way Bill QR Code */}
           <QRCode 
             value={eWayBillData.eway_bill_no || `EWB:${eWayBillData.document_number}|DT:${eWayBillData.document_date}|GST:${profile.gstin}`}
             size={65}
             style={{ height: "auto", maxWidth: "100%", width: "100%" }}
             viewBox={`0 0 256 256`}
           />
           <span className="text-[6px] font-bold text-black uppercase mt-1">Scan to Verify</span>
        </div>
      </div>

      <div className="border border-black mb-4 p-2">
         <div className="grid grid-cols-2 gap-4">
            <div className="font-bold text-base">e-Way Bill No: {eWayBillData.eway_bill_no || '122610... (Pending)'}</div>
            <div className="text-right font-bold text-base">Generated Date: {format(new Date(eWayBillData.document_date), 'dd/MM/yyyy')}</div>
            <div className="font-bold">Generated By: {profile.gstin} - {profile.company_name}</div>
            <div className="text-right font-bold">Valid Until: {eWayBillData.valid_until || format(new Date(), 'dd/MM/yyyy')} 23:59:59 (1 Day)</div>
         </div>
      </div>

      {/* Part A */}
      <div className="border border-black mb-4">
         <div className="bg-slate-50 border-b border-black p-1 text-center font-bold uppercase tracking-widest text-sm">Part-A</div>
         
         <div className="grid grid-cols-2 gap-0 border-b border-black avoid-break">
            <div className="p-2 border-r border-black">
               <h4 className="font-bold border-b border-slate-200 text-[10px] mb-1">Details of Consignor:</h4>
               <div className="text-[10px] space-y-0.5">
                  <p><span className="w-16 inline-block font-bold">GSTIN:</span> {eWayBillData.from_gstin || profile.gstin}</p>
                  <p><span className="w-16 inline-block font-bold">Name:</span> {profile.company_name}</p>
                  <p><span className="w-16 inline-block font-bold text-slate-500">Address:</span> {eWayBillData.from_address || profile.business_address}</p>
               </div>
            </div>
            <div className="p-2">
               <h4 className="font-bold border-b border-slate-200 text-[10px] mb-1">Details of Consignee:</h4>
               <div className="text-[10px] space-y-0.5">
                  <p><span className="w-16 inline-block font-bold">Name:</span> {client.name}</p>
                  {!client.hide_contact_details && (
                    <>
                      <p><span className="w-16 inline-block font-bold">GSTIN:</span> {eWayBillData.to_gstin || client.gstin}</p>
                      <p><span className="w-16 inline-block font-bold text-slate-500">Address:</span> {eWayBillData.to_address || client.address} PIN: {client.postal_code}</p>
                    </>
                  )}
               </div>
            </div>
         </div>

         <div className="p-2 bg-slate-50 border-b border-black font-bold text-[10px]">Document Details:</div>
         <div className="grid grid-cols-3 gap-0 border-b border-black text-[10px]">
            <div className="p-2 border-r border-black">Doc Type: <span className="font-bold uppercase">{eWayBillData.document_type}</span></div>
            <div className="p-2 border-r border-black">Doc No: <span className="font-bold">{eWayBillData.document_number}</span></div>
            <div className="p-2">Doc Date: <span className="font-bold">{format(new Date(eWayBillData.document_date), 'dd/MM/yyyy')}</span></div>
         </div>

         <div className="grid grid-cols-2 gap-0 border-b border-black text-[10px]">
            <div className="p-2 border-r border-black">Transaction Type: <span className="font-bold uppercase">{eWayBillData.transaction_type}</span></div>
            <div className="p-2 font-bold text-right text-base px-4">Value: ₹{eWayBillData.total_value.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</div>
         </div>

         <div className="p-2">
            <h4 className="font-bold underline text-[10px] mb-2">Item Details:</h4>
            <table className="w-full border-collapse border border-black text-[9px]">
               <thead className="bg-slate-100">
                  <tr className="text-center font-bold">
                     <th className="border border-black p-1 w-8">Sl.</th>
                     <th className="border border-black p-1">Product Name & Description</th>
                     <th className="border border-black p-1 w-20">HSN Code</th>
                     <th className="border border-black p-1 w-16">Quantity</th>
                     <th className="border border-black p-1 w-24">Taxable Value</th>
                  </tr>
               </thead>
               <tbody>
                  {items.map((item, idx) => (
                     <tr key={idx} className="text-center avoid-break">
                        <td className="border border-black p-1">{idx + 1}</td>
                        <td className="border border-black p-1 text-left font-bold">{item.product_name}</td>
                        <td className="border border-black p-1 font-mono">{item.hsn_code}</td>
                        <td className="border border-black p-1">{item.quantity} {item.unit}</td>
                        <td className="border border-black p-1">₹{item.value.toFixed(2)}</td>
                     </tr>
                  ))}
               </tbody>
            </table>
         </div>
      </div>

      {/* Part B */}
      <div className="border border-black mb-4 avoid-break">
         <div className="bg-slate-50 border-b border-black p-1 text-center font-bold uppercase tracking-widest text-sm">Part-B</div>
         <table className="w-full text-center text-[10px] border-collapse">
            <thead className="bg-slate-100">
               <tr className="font-bold">
                  <th className="border-r border-black p-2">Transport Mode</th>
                  <th className="border-r border-black p-2">Vehicle / Transporter ID</th>
                  <th className="border-r border-black p-2">Doc No & Date</th>
                  <th className="p-2">Distance (Approx)</th>
               </tr>
            </thead>
            <tbody>
               <tr className="font-bold text-sm">
                  <td className="border-r border-black p-4 uppercase">{eWayBillData.transport_mode}</td>
                  <td className="border-r border-black p-4 text-blue-900 font-mono tracking-widest">{eWayBillData.vehicle_number || eWayBillData.transporter_name || 'N/A'}</td>
                  <td className="border-r border-black p-4">{eWayBillData.document_number} {format(new Date(eWayBillData.document_date), 'dd/MM/yyyy')}</td>
                  <td className="p-4">{eWayBillData.distance || '0'} KM</td>
               </tr>
            </tbody>
         </table>
      </div>

      <div className="flex justify-between items-start mt-8 border-t border-slate-100 pt-6 avoid-break">
         <div className="w-[65%] text-[9px] text-slate-500 leading-tight">
            <p className="font-bold mb-1 underline">Instruction:</p>
            <ul className="list-disc list-inside space-y-1">
               <li>This e-Way Bill is generated as per the information provided.</li>
               <li>Vehicle details are updated for {eWayBillData.transport_mode} movement.</li>
               <li>Verify all details before commencement of transport.</li>
               <li>Validity is extended till next midnight based on distance.</li>
            </ul>
         </div>
         <div className="w-[30%] text-right border-t border-black pt-2 pr-2">
            <p className="font-bold text-[9px] mb-2 uppercase">Official Transport Stamp</p>
            <div className="h-20 w-full relative flex items-center justify-end overflow-hidden">
               <DigitalStamp />
            </div>
            <p className="text-[8px] font-bold text-slate-400 mt-2 italic uppercase">System Authenticated via Invoice Plus</p>
         </div>
      </div>

      <div className="mt-auto pt-4 text-center text-[8px] font-bold uppercase tracking-[0.5em] text-slate-300">
         Digital Logistics Management System • {format(new Date(), 'yyyy')}
      </div>
    </div>
  );
};
